import { useQuery } from '@tanstack/react-query'
import { WandSparkles } from 'lucide-react'

import { api } from '../api/client'
import type { ArtifactKind, SourceQuestion } from '../api/study'
import type { KeyPoint } from '../api/keypoints'

const kindLabels: Record<ArtifactKind, string> = { outline: '复习提纲', flashcard: '记忆卡', ai_new: 'AI 新题', ai_variant: '原题变式', ai_error_cause: '错因题' }

export function ArtifactGenerator({ kind, onKindChange, points, questions, selectedPointIds, selectedQuestionIds, onPointIdsChange, onQuestionIdsChange, providerId, modelId, onProviderChange, onModelChange, prompt, onPromptChange, pending, onGenerate }: { kind: ArtifactKind; onKindChange: (kind: ArtifactKind) => void; points: KeyPoint[]; questions: SourceQuestion[]; selectedPointIds: number[]; selectedQuestionIds: number[]; onPointIdsChange: (ids: number[]) => void; onQuestionIdsChange: (ids: number[]) => void; providerId: string; modelId: string; onProviderChange: (id: string) => void; onModelChange: (id: string) => void; prompt: string; onPromptChange: (value: string) => void; pending: boolean; onGenerate: () => void }) {
  const providers = useQuery({ queryKey: ['providers'], queryFn: api.listProviders })
  const models = useQuery({ queryKey: ['provider-models', providerId], queryFn: () => api.listModels(providerId), enabled: Boolean(providerId) })
  const needsQuestion = kind === 'ai_variant' || kind === 'ai_error_cause'
  const missing = !selectedPointIds.length ? '请至少选择一个已确认重点。' : needsQuestion && !selectedQuestionIds.length ? '变式题和错因题必须选择原题。' : !providerId || !modelId ? '请选择已启用服务和已校验模型。' : ''
  function toggle(values: number[], id: number, checked: boolean) { return checked ? [...new Set([...values, id])] : values.filter((value) => value !== id) }
  return <section className="artifact-generator"><div className="section-heading"><div><p className="eyebrow">按需生成</p><h2>选择这次要复习的内容</h2></div></div><label>输出类型<select value={kind} onChange={(event) => onKindChange(event.target.value as ArtifactKind)}>{Object.entries(kindLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><fieldset><legend>已确认重点</legend>{points.map((point) => <label className="check-row" key={point.id}><input type="checkbox" checked={selectedPointIds.includes(point.id)} onChange={(event) => onPointIdsChange(toggle(selectedPointIds, point.id, event.target.checked))} /><span>{point.title}</span></label>)}</fieldset>{needsQuestion && <fieldset><legend>原题依据</legend>{questions.map((question) => <label className="check-row" key={question.id}><input type="checkbox" checked={selectedQuestionIds.includes(question.id)} onChange={(event) => onQuestionIdsChange(toggle(selectedQuestionIds, question.id, event.target.checked))} /><span>{question.question_text}</span></label>)}</fieldset>}<div className="form-grid"><label>第三方服务<select value={providerId} onChange={(event) => { onProviderChange(event.target.value); onModelChange('') }}><option value="">请选择</option>{providers.data?.filter((item) => item.enabled).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>模型<select value={modelId} onChange={(event) => onModelChange(event.target.value)} disabled={!providerId}><option value="">请选择</option>{models.data?.filter((item) => item.structured_status === 'passed').map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label></div><label>本次生成要求（可选）<textarea value={prompt} onChange={(event) => onPromptChange(event.target.value)} /></label>{missing && <p className="field-hint" role="note">{missing}</p>}<button className="button button--primary" type="button" disabled={Boolean(missing) || pending} onClick={onGenerate}><WandSparkles /> 生成{kindLabels[kind]}</button></section>
}
